### ISSUE TITLE
Crash in debug builds

### ISSUE THREAD

**Issue by kvolkers** [bitmovin/bitmovin-player-android-analytics-conviva#55] opened 2024-03-28 15:35 UTC
Running into the attached crash ~~on Android 6. More recent Android versions do work~~ in debug builds on a variety of OS versions. Release builds do not seem to be affected.

[bitmovin_conviva_integration_crash.txt](https://github.com/bitmovin/bitmovin-player-android-analytics-conviva/files/14791870/bitmovin_conviva_integration_crash.txt)
```
java.lang.NoSuchMethodError: No static method getSdkVersion()Ljava/lang/String; in class Lcom/bitmovin/player/api/Player; or its super classes (declaration of 'com.bitmovin.player.api.Player' appears in /data/app/nl.nlziet.debug-1/base.apk:classes19.dex)
```

![image](https://github.com/bitmovin/bitmovin-player-android-analytics-conviva/assets/22174865/22ba08fe-d11e-469d-afd9-25a9d1fa655f)

![image](https://github.com/bitmovin/bitmovin-player-android-analytics-conviva/assets/22174865/566be8d2-dd52-4722-b63a-b1da04ee2207)

Seems related to a change from last August.

Devices:
- Samsung Galaxy A5 on Android 6.0.1
- Emulator API 23 Android 6

Used dependencies:
```
    const val bitmovin = "com.bitmovin.player:player:3.61.0"
    const val bitmovinConviva = "com.bitmovin.analytics:conviva:2.2.0"
```

**Comment by kvolkers** [comment] 2024-05-31 13:55
Managed to reproduce it in the sample app running on Emulator API 23 Android 6.

Sample app crash log:
[sample_player_version_crash.txt](https://github.com/user-attachments/files/15514588/sample_player_version_crash.txt)

Modified sample app:
https://github.com/kvolkers/bitmovin-player-android-analytics-conviva/tree/reproduce/player-version-crash

**Comment by strangesource** [comment] 2024-06-05 07:16
Hi @kvolkers, thanks for providing the reproduction scenario. I was able to use it to see the behaviour you described. 
I don't know the exact root cause but it suspect that it is an issue related to how the artefact is published.

In the upcoming release we include some improvements for that and I expect the issue to be resolved. I'll let you know once the new version is released.

**Comment by strangesource** [comment] 2024-06-06 11:47
The latest version https://github.com/bitmovin/bitmovin-player-android-analytics-conviva/releases/tag/v2.4.0 is now available, please check if you can still reproduce the issue.

**Comment by kvolkers** [comment] 2024-06-06 12:22
Hi @strangesource, I can confirm in the latest version I'm no longer experiencing this crash 👍

**Comment by strangesource** [comment] 2024-06-06 12:23
Thanks, closing the issue.

**Closed by strangesource** 2024-06-06 12:23 UTC
